spring:
  application:
    name: smartBill
  jackson:
    default-property-inclusion: non-null
  datasource:
    url: jdbc:postgresql://localhost:5432/smartbill
    username: postgres
    password: 5421
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  thymeleaf:
    cache: false
  mail:
    host:
      smtp.gmail.com
    port:
      587
    username:
      smartbillnoreply@gmail.com
    password:
      fxthhqkwydgjzemu
    properties:
      mail:
        smtp:
          auth:
            true
          starttls:
            enable:
              true
          ssl:
            trust:
              smtp.gmail.com
logging:
  level:
    org.hibernate.SQL: debug

api:
  security:
    secret: 5421